---
title: "DATA1001/1901 Lab9"
subtitle: "Sample Surveys"
author: "© University of Sydney 2021"
output:
  html_document:
    theme: flatly
    number_sections: yes
    toc: true
    toc_float: true
    toc_depth: 4
    code_folding: show
---
<style>
h2 { /* Header 2 */
    font-size: 22px
}
</style>

<style>
h3 { /* Header 3 */
    font-size: 18px
}
</style>

<br>

# Live Demo {-}

We will demonstrate how to model a sample survey in R.

# Coding Challenge

Below is a worked example of a box. Use this example to find the area under the normal curve for:

- Box with c(1,3,5) as options

- n = 10

- between points 25 and 20

And visualise the area under the normal curve in base R.
```{r}
box=c(1,0)
m = 10 * mean(box)
s = sqrt(10) * sd(box) * (sqrt(1)/sqrt(2))
threshold1 = 5
threshold2 = 6
pnorm(6, m, s) - pnorm(5, m, s)

xlimits1 = seq(round(-4 * s + m, digit = -1), round(4 * s + m, digit = -1), 
1)
curve(dnorm(x, mean = m, sd = s), m - 4 * s, m + 4 * s, col = "indianred", lwd = 2, 
xlab = "", ylab = "", main = "P(sum is between 5 and 6)", axes = F)
sequence <- seq(threshold1, threshold2, 0.1)
polygon(x = c(sequence, threshold2, threshold1), y = c(dnorm(c(sequence), m, 
s), 0, 0), col = "indianred")
axis(1, xlimits1, line = 1, col = "black", col.ticks = "black", col.axis = "black")
mtext("sum of box", 1, line = 1, at = -2, col = "black")
axis(1, xlimits1, labels = round((xlimits1 - m)/s, 2), line = 3.3, col = "indianred1", 
col.ticks = "indianred1", col.axis = "indianred1")
mtext("Z score", 1, line = 3.3, at = -2, col = "indianred1")
```

solution
```{r}
box=c(1,3,5)
m = 10 * mean(box)
s = sqrt(10) * sd(box) * (sqrt(1)/sqrt(2))
threshold1 = 20
threshold2 = 25
pnorm(25, m, s) - pnorm(20, m, s)

xlimits1 = seq(round(-4 * s + m, digit = -1), round(4 * s + m, digit = -1), 
1)
curve(dnorm(x, mean = m, sd = s), m - 4 * s, m + 4 * s, col = "indianred", lwd = 2, 
xlab = "", ylab = "", main = "P(sum is between 20 and 25)", axes = F)
sequence <- seq(threshold1, threshold2, 0.1)
polygon(x = c(sequence, threshold2, threshold1), y = c(dnorm(c(sequence), m, 
s), 0, 0), col = "indianred")
axis(1, xlimits1, line = 1, col = "black", col.ticks = "black", col.axis = "black")
mtext("sum of box", 1, line = 1, at = -2, col = "black")
axis(1, xlimits1, labels = round((xlimits1 - m)/s, 2), line = 3.3, col = "indianred1", 
col.ticks = "indianred1", col.axis = "indianred1")
mtext("Z score", 1, line = 3.3, at = -2, col = "indianred1")
```

